/* Automatically generated by IntelliJ IDEA from Java, revision needed before production use */
/*
 * Copyright (c) 2008, Vaclav Slovacek. All Rights Reserved.
 *
 * Product: UIProtocol Java
 *
 * This source-code is released under following license:
 * - no release outside i2home project is allowed
 * - this copyright notice must be placed unmodified in every file derived from this source code
 */


//@todo make compatible with actionscript

package uidocument.commons.api.document {
/**
 * Type of executed action deciding whether the action will be executed only on client side via model updates
 */
public final class ActionType {
    /*
     pub static final var CLIENT:ActionType;
     pub static final var SERVER:ActionType;
     */
}
}