/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.dialog {
	import laya.ui.*;
	import laya.display.*;

	public class SettleUI extends Dialog {
		public var settleList:List;
		public var btnRestart:Button;

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"Dialog","props":{"width":1140,"height":855},"compId":2,"child":[{"type":"Image","props":{"y":427,"x":570,"skin":"settle/settle_panel.png","anchorY":0.5,"anchorX":0.5},"compId":11},{"type":"List","props":{"y":427,"x":570,"width":540,"var":"settleList","repeatY":3,"repeatX":1,"name":"settleList","height":250,"anchorY":0.5,"anchorX":0.5},"compId":3,"child":[{"type":"Box","props":{"renderType":"render","height":70},"compId":4,"child":[{"type":"Image","props":{"skin":"settle/liebiao1.png","name":"diban"},"compId":5,"child":[{"type":"Label","props":{"y":18,"x":30,"valign":"middle","text":"名字","overflow":"hidden","name":"name","fontSize":30,"font":"Microsoft YaHei","color":"#666666","align":"left"},"compId":6},{"type":"Label","props":{"y":18,"x":236,"valign":"middle","text":"倍数","overflow":"hidden","name":"double","fontSize":30,"font":"Microsoft YaHei","color":"#666666","align":"left"},"compId":7},{"type":"Label","props":{"y":18,"x":440,"valign":"middle","text":"得分","overflow":"hidden","name":" score","fontSize":30,"font":"Microsoft YaHei","color":"#666666","align":"left"},"compId":8}]}]}]},{"type":"Button","props":{"y":560,"x":436,"var":"btnRestart","stateNum":2,"skin":"button/btn_zailai.png","name":"sure"},"compId":10},{"type":"Button","props":{"stateNum":2,"skin":"button/btn_fanhui.png","name":"close"},"compId":9}],"loadList":["settle/settle_panel.png","settle/liebiao1.png","button/btn_zailai.png","button/btn_fanhui.png"],"loadList3D":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}