/* Automatically generated by IntelliJ IDEA from Java, revision needed before production use */
/*
 * Copyright (c) 2008, Vaclav Slovacek. All Rights Reserved.
 *
 * Product: UIProtocol Java
 *
 * This source-code is released under following license:
 * - no release outside i2home project is allowed
 * - this copyright notice must be placed unmodified in every file derived from this source code
 */


package uidocument.commons.api.document {

/**
 * Class providing access to
 */
public class Position extends Property {

    public function Position(property:Property) {
        super(property);
    }

    public function getX():Number {
        return getNumberValue(1);
        //if (this.x == -1) return 0;
        //return this.x;
    }

    public function getY():Number {
        return getNumberValue(2);
        //if (this.y == -1) return 0;
        //return this.y;
    }

    public function getWidth():Number {
        return getNumberValue(3);
        //if (getNumberValue(3) == -1) return 200;
        //return getNumberValue(3);
    }

    public function getHeight():Number {
        return getNumberValue(4);
        //if (getNumberValue(4) == -1) return 70;
        //return getNumberValue(4);
    }

    override public function toString():String {
        return "X:" + getX() + ",Y:" + getY() + ",Width:" + getWidth() + ",Height:" + getHeight();
    }

}
}