/* Automatically generated by IntelliJ IDEA from Java, revision needed before production use */

//@todo make compatible with actionscript

package uidocument.commons.api.document {
public final class ActionAccess {
    /*
     pub static final var SYSTEM:ActionAccess;

     pub static final var USER:ActionAccess;
     */
}
}