/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package {
	import laya.utils.ClassUtils;
	import laya.ui.View;
	import laya.webgl.WebGL;
	import game.script.DealScript;
	import game.script.BottomListScript;
	import game.script.SurfaceScript;
	import game.script.ClockScript;
	import game.script.MarkScript;
	import game.script.OwnerListScript;
	import game.script.ControlScript;
	import game.script.ThrowListScript;
	import game.script.MenuScript;
	import game.script.GameScript;
	import main.runtime.RoomBtnRunTime;
	import main.script.Room;
	import main.script.Menu;
	/**
	 * 游戏初始化配置
	 */
	public class GameConfig {
		public static var width:int = 1140;
		public static var height:int = 855;
		public static var scaleMode:String = "showall";
		public static var screenMode:String = "horizontal";
		public static var alignV:String = "middle";
		public static var alignH:String = "center";
		public static var startScene:* = "main.scene";
		public static var sceneRoot:String = "";
		public static var debug:Boolean = false;
		public static var stat:Boolean = false;
		public static var physicsDebug:Boolean = false;
		public static var exportSceneToJson:Boolean = true;
		
		public static function init():void {
			//注册Script或者Runtime引用
			var reg:Function = ClassUtils.regClass;
			reg("game.script.DealScript",DealScript);
			reg("game.script.BottomListScript",BottomListScript);
			reg("game.script.SurfaceScript",SurfaceScript);
			reg("game.script.ClockScript",ClockScript);
			reg("game.script.MarkScript",MarkScript);
			reg("game.script.OwnerListScript",OwnerListScript);
			reg("game.script.ControlScript",ControlScript);
			reg("game.script.ThrowListScript",ThrowListScript);
			reg("game.script.MenuScript",MenuScript);
			reg("game.script.GameScript",GameScript);
			reg("main.runtime.RoomBtnRunTime",RoomBtnRunTime);
			reg("main.script.Room",Room);
			reg("main.script.Menu",Menu);
		}
		GameConfig.init();
	}
}