/* Automatically generated by IntelliJ IDEA from Java, revision needed before production use */
/*
 * Copyright (c) 2008, Vaclav Slovacek. All Rights Reserved.
 *
 * Product: UIProtocol Java
 *
 * This source-code is released under following license:
 * - no release outside i2home project is allowed
 * - this copyright notice must be placed unmodified in every file derived from this source code
 */





// @todo class attribute

package uidocument.commons.api.document {

import flash.xml.XMLNode;

public class Layout {


    private var id:String;

    function Layout(node:XMLNode) {
        this.id = "LAYOUT";
    }

    // @todo consider renaming to getLayoutClass
    // @todo missing class Described
    /**
     * Retrieves layout classes.
     *
     * @return layout classes.
     */
    public function getLayoutId():String {
        return this.id;
    }

    ;
}
}