/* Automatically generated by IntelliJ IDEA from Java, revision needed before production use */
/*
 * Copyright (c) 2008, Vaclav Slovacek. All Rights Reserved.
 *
 * Product: UIProtocol Java
 *
 * This source-code is released under following license:
 * - no release outside i2home project is allowed
 * - this copyright notice must be placed unmodified in every file derived from this source code
 */


package uidocument.commons.api.document {

public class Behavior {

    private var trigger:String;
    private var name:String;
    private var properties:Property;

    function Behavior(trigger:String, name:String, properties:Property) {
        this.trigger = trigger;
        this.name = name;
        this.properties = properties;
    }

    /**
     * Specified in which circumstances the action is executed.
     *
     * @return trigger causing the action to execute
     */
    public function getTrigger():String {
        return this.trigger;
    }

    ;

    /**
     * Retrieves action that is executed after trigger is triggered.
     *
     * @return name of the action to be executed
     */
    public function getAction():String {
        return this.name;
    }

    ;

    public function getProperties():Property {
        return this.properties;
    }

    /**
     * Tells whether implicit properties should be added to the event send to server.
     *
     * @return true if implicit properties should be added to the event
     */
    public function addImplicitProperties():Boolean {
        return (properties.getLength() == 0);
    }

    ;

    public function toString():String {
        return "trigger:"+trigger+",name:"+name+"\n"
    }
}
}